# Generated by Django 5.1.1 on 2024-11-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantineApp', '0002_bill_remove_expense_date_remove_sale_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
