# Generated by Django 5.1.1 on 2024-11-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantineApp', '0006_accounting_sale_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='is_credit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
