version: "3.8"

services:
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=cantine.settings
      - DEBUG=0
      - ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
