{
  "Version": "2012-10-17",
  "Statement":
    [
      {
        "Effect": "Allow",
        "Action":
          [
            "elasticbeanstalk:*",
            "ec2:*",
            "s3:*",
            "autoscaling:*",
            "iam:CreateRole",
            "iam:PassRole",
          ],
        "Resource": "*",
      },
      {
        "Effect": "Allow",
        "Action": "iam:PassRole",
        "Resource": "arn:aws:iam::850995532696:role/aws-elasticbeanstalk-ec2-role",
      },
    ],
}
